export default Object.freeze({
    FETCH_MOVIES:             'FETCH_MOVIES',
    FETCH_MOVIES_SUCCESS:     'FETCH_MOVIES_SUCCESS',
    FETCH_MOVIES_FAIL:        'FETCH_MOVIES_FAIL',
    FETCH_FULL_MOVIE:         'FETCH_FULL_MOVIE',
    FETCH_FULL_MOVIE_SUCCESS: 'FETCH_FULL_MOVIE_SUCCESS',
    FETCH_FULL_MOVIE_FAIL:    'FETCH_FULL_MOVIE_FAIL',
    ADD_MOVIE:                'ADD_MOVIE',
    ADD_MOVIE_SUCCESS:        'ADD_MOVIE_SUCCESS',
    ADD_MOVIE_FAIL:           'ADD_MOVIE_FAIL',
    DELETE_MOVIE:             'DELETE_MOVIE',
    DELETE_MOVIE_SUCCESS:     'DELETE_MOVIE_SUCCESS',
    DELETE_MOVIE_FAIL:        'DELETE_MOVIE_FAIL',
    FETCH_MY_LIST:            'FETCH_MY_LIST',
    FETCH_MY_LIST_SUCCESS:    'FETCH_MY_LIST_SUCCESS',
    FETCH_MY_LIST_FAIL:       'FETCH_MY_LIST_FAIL'
});
